In [1]:
inp = [4,-2,3.5,5,-11,-4.7]

In [2]:
weights = 6

In [3]:
import numpy
pop = 8
size = (pop,weights)
new= numpy.random.uniform(low=-4.0, high=4.0, size=size)

In [4]:
new

array([[-1.4818599 , -2.89541943,  3.36503459, -3.05733084, -0.39656192,
        -0.93564636],
       [-3.47727064,  0.7220233 ,  3.33372869,  3.28949801, -1.56400994,
        -0.14171896],
       [-3.58689984,  0.53907456, -0.26064411,  0.04491667, -1.64721355,
        -1.37904999],
       [-3.82323597,  2.39108747,  0.0047618 , -3.50081534, -0.88699216,
         2.56905353],
       [ 2.53906165,  0.67108367,  3.97621926, -2.49108917,  0.07707299,
         2.65930702],
       [ 0.20330473,  3.67589621,  3.1640694 ,  2.38951556, -1.63871454,
         2.95455297],
       [ 0.65525274,  1.66138574,  3.75526287, -2.1884857 , -2.07357193,
         1.59955355],
       [ 2.83619258, -1.21296205,  2.00927272, -1.05508322,  1.29651239,
         2.16593863]])

In [5]:
def cal_pop_fitness(inp, pop):
    fitness = numpy.sum(pop*inp, axis=1)
    return fitness

In [6]:
def select_mating_pool(pop, fitness, numParents):
    par = numpy.empty((numParents, pop.shape[1]))
    for num in range(numParents):
        max_fitness_idx = numpy.where(fitness == numpy.max(fitness))
        max_fitness_idx = max_fitness_idx[0][0]
        par[num, :] = pop[max_fitness_idx, :]
        fitness[max_fitness_idx] = -99999999999
    return par

In [7]:
def crossover(parents, offspring_size):
    offspring = numpy.empty(offspring_size)
    crossover_point = numpy.uint8(offspring_size[1]/2)
    for k in range(offspring_size[0]):
        parent1_idx = k%parents.shape[0]
        parent2_idx = (k+1)%parents.shape[0]
        offspring[k, 0:crossover_point] = parents[parent1_idx, 0:crossover_point]
        offspring[k, crossover_point:] = parents[parent2_idx, crossover_point:]
    return offspring

In [8]:
def perform_mutation(offspring_crossover):
    for idx in range(offspring_crossover.shape[0]):
        random_value = numpy.random.uniform(-1.0, 1.0, 1)
        offspring_crossover[idx, 4] = offspring_crossover[idx, 4] + random_value
    return offspring_crossover

In [9]:
gen = 5
parents_mating = 4
for generation in range(gen):
    fitness = cal_pop_fitness(inp, new)
    par = select_mating_pool(new, fitness, parents_mating)
    cross = crossover(par, offspring_size=(size[0]-par.shape[0], weights))
    mutation_result = perform_mutation(cross)  # Rename the 'mutation' function to avoid conflict
    new[0:par.shape[0], :] = par
    new[par.shape[0]:, :] = mutation_result

In [10]:
new

array([[ 0.65525274,  1.66138574,  3.75526287,  3.28949801, -3.03416977,
        -0.14171896],
       [ 0.65525274,  1.66138574,  3.75526287,  0.04491667, -2.94879204,
        -1.37904999],
       [ 0.65525274,  1.66138574,  3.75526287,  3.28949801, -1.57909904,
        -0.14171896],
       [ 0.65525274,  1.66138574,  3.75526287,  3.28949801, -1.49640466,
        -0.14171896],
       [ 0.65525274,  1.66138574,  3.75526287,  0.04491667, -1.98933989,
        -1.37904999],
       [ 0.65525274,  1.66138574,  3.75526287,  3.28949801, -1.02510922,
        -0.14171896],
       [ 0.65525274,  1.66138574,  3.75526287,  3.28949801, -0.6639903 ,
        -0.14171896],
       [ 0.65525274,  1.66138574,  3.75526287,  3.28949801, -2.28814978,
        -0.14171896]])

In [11]:
par

array([[ 0.65525274,  1.66138574,  3.75526287,  3.28949801, -3.03416977,
        -0.14171896],
       [ 0.65525274,  1.66138574,  3.75526287,  0.04491667, -2.94879204,
        -1.37904999],
       [ 0.65525274,  1.66138574,  3.75526287,  3.28949801, -1.57909904,
        -0.14171896],
       [ 0.65525274,  1.66138574,  3.75526287,  3.28949801, -1.49640466,
        -0.14171896]])

In [12]:
mutation_result

array([[ 0.65525274,  1.66138574,  3.75526287,  0.04491667, -1.98933989,
        -1.37904999],
       [ 0.65525274,  1.66138574,  3.75526287,  3.28949801, -1.02510922,
        -0.14171896],
       [ 0.65525274,  1.66138574,  3.75526287,  3.28949801, -0.6639903 ,
        -0.14171896],
       [ 0.65525274,  1.66138574,  3.75526287,  3.28949801, -2.28814978,
        -0.14171896]])